name: KarmicLives
main: com.mitsugaru.karmiclives.KarmicLives
version: 0.01
authors:
 - Mitsugaru
depend: [Vault]

commands:
    lives:
        description: Root command.
        usage: /<command>

permissions:
    KarmicLives.all:
        description: Gives all permission nodes.
        default: false
        children:
            KarmicLives.buy: true
            KarmicLives.sell: true
            KarmicLives.trade: true
            KarmicLives.use: true
            KarmicLives.view: true
            KarmicLives.admin: true
            KarmicLives.ignore.cost: true
            KarmicLives.ignore.death: true
            KarmicLives.ignore.cooldown: true
    KarmicLives.buy:
        description: Allows a player to buy lives.
        default: false
    KarmicLives.sell:
        description: Allows players to sell lives for money.
        default: false
    KarmicLives.trade:
        description: Allows players to send lives to other players.
        default: false
    KarmicLives.use:
        description: Makes a player use the lives system.
        default: false
    KarmicLives.cooldown:
        description: Enforces cooldown rule if enabled in the config.
        default: false
    KarmicLives.view:
        description: Allows user to view other player's lives
        default: false
    KarmicLives.admin:
        description: Administrate the plugin.
        default: op
        children:
            KarmicLives.view: true
    KarmicLives.ignore.all:
        description: Adds all ignore nodes.
        default: false
        children:
            KarmicLives.ignore.cost: true
            KarmicLives.ignore.death: true
            KarmicLives.ignore.cooldown: true
    KarmicLives.ignore.cost:
        description: Ignores the cost for buying / selling lives.
        default: false
    KarmicLives.ignore.death: 
        description: Ignores the lives usage on death.
        default: false
    KarmicLives.ignore.cooldown: 
        description: Ignores the cooldown.
        default: false